# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QInputDialog


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(754, 462)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 30, 651, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.devSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.devSelect.setObjectName("devSelect")
        self.devSelect.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.horizontalLayout.addWidget(self.devSelect)
        self.beginBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.beginBtn.setObjectName("beginBtn")
        self.horizontalLayout.addWidget(self.beginBtn)
        self.stopBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout.addWidget(self.stopBtn)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(50, 100, 651, 331))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.setStretch(0,1)
        self.horizontalLayout.setStretch(1,4)
        self.horizontalLayout.setStretch(2,1)


        self.retranslateUi(Dialog)
        self.beginBtn.clicked.connect(Dialog.beginSniff)
        self.stopBtn.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "选择设备"))
        self.beginBtn.setText(_translate("Dialog", "开始抓包"))
        self.stopBtn.setText(_translate("Dialog", "停止"))


